- project:
    templates:
      - designate-devstack-jobs
      - openstack-python-jobs
      - publish-openstack-sphinx-docs
      - check-requirements
      - openstackclient-plugin-jobs
      - openstack-python35-jobs
    check:
      jobs:
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-lower-constraints
    post:
      jobs:
        - openstack-tox-cover
