- project:
    templates:
      - check-requirements
      - designate-devstack-jobs
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
    gate:
      queue: designate
